# Generated by Django 6.0.2 on 2026-02-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consolidate_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apioperation',
            name='action',
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('tenant', 'tenant_module')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'tenant')},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='action',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
