# Generated by Django 6.0.2 on 2026-02-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_action_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='apioperation',
            name='required_permission_code',
            field=models.CharField(default='READ', max_length=100),
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_code',
            field=models.CharField(default='FULL', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('tenant', 'tenant_module', 'permission_code')},
        ),
    ]
