# Generated by Django 6.0.2 on 2026-02-16 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update_permission_code_architecture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set(),
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='submodule',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='apioperation',
            name='required_permission_code',
        ),

        migrations.AddField(
            model_name='apioperation',
            name='permission_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.module'),
        ),
        migrations.AddField(
            model_name='permission',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submodule'),
        ),
        migrations.AddField(
            model_name='submodule',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='submodule',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modulesubmodulemapping',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='core.module'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permission_code',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='tenant_module',
        ),
        migrations.CreateModel(
            name='TenantApiPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('api_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apioperation')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'api_operation')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('tenant', 'module', 'submodule', 'code')},
        ),
    ]
