# Generated by Django 6.0.1 on 2026-01-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='approved',
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
    ]
