# Generated by Django 6.0.1 on 2026-01-27 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('enquiry', '0003_alter_enquiry_options_and_more'),
        ('quotation', '0002_remove_quotation_approved_quotation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='quotation',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['tenant', 'status'], name='quotation_q_tenant__6f5318_idx'),
        ),
    ]
