# Generated by Django 6.0.1 on 2026-02-03 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='organizatio_status_99f5be_idx')],
            },
        ),
    ]
