# Generated by Django 4.2.27 on 2026-02-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'admin_action',
            },
        ),
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'admin_api_details',
            },
        ),
        migrations.CreateModel(
            name='ApiOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_method', models.CharField(max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.action')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apiendpoint')),
            ],
            options={
                'db_table': 'admin_api_operation',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_module',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.action')),
            ],
            options={
                'db_table': 'admin_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_sub_module',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='core.module')),
                ('submodule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submodule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.tenant')),
            ],
            options={
                'db_table': 'admin_tenant_module',
            },
        ),
        migrations.CreateModel(
            name='TenantApiOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('api_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apioperation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'admin_tenant_api_operation',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role')),
            ],
            options={
                'db_table': 'admin_role_permission_mapping',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='permission',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='permission',
            name='tenant_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenantmodule'),
        ),
        migrations.CreateModel(
            name='ModuleSubModuleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module')),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.submodule')),
            ],
            options={
                'db_table': 'admin_mod_submodule_mapping',
            },
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submodule'),
        ),
        migrations.AddConstraint(
            model_name='tenantmodule',
            constraint=models.UniqueConstraint(fields=('tenant', 'module', 'submodule'), name='unique_tenant_module_submodule'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantapioverride',
            unique_together={('tenant', 'api_operation')},
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('tenant', 'tenant_module', 'action')},
        ),
        migrations.AlterUniqueTogether(
            name='modulesubmodulemapping',
            unique_together={('module', 'submodule')},
        ),
        migrations.AlterUniqueTogether(
            name='apioperation',
            unique_together={('endpoint', 'http_method')},
        ),
    ]
