# Generated by Django 4.2.27 on 2026-02-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='admin_role',
        ),
    ]
