# Generated by Django 6.0.1 on 2026-01-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('DISQUALIFIED', 'Disqualified'), ('CLOSED', 'Closed')], default='NEW', max_length=20),
        ),
    ]
