# Generated by Django 6.0.1 on 2026-01-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('enquiry', '0002_enquiry_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['tenant', 'status'], name='enquiry_enq_tenant__853fa8_idx'),
        ),
    ]
