# Generated by Django 6.0.1 on 2026-01-27 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('enquiry', '0003_alter_enquiry_options_and_more'),
        ('followup', '0002_followup_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='followup',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['tenant', 'status'], name='followup_fo_tenant__9f786b_idx'),
        ),
    ]
