# Generated by Django 6.0.1 on 2026-01-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('followup', '0004_backfill_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.tenant'),
        ),
    ]
