# Generated by Django 6.0.2 on 2026-03-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
        ('core', '0006_alter_module_options_alter_submodule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_users', to='core.tenant'),
        ),
    ]
